# Generated by Django 5.2 on 2025-04-25 05:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagereadstatus',
            index=models.Index(fields=['user', 'message'], name='chat_room_m_user_id_85d402_idx'),
        ),
    ]
