# Generated by Django 5.2 on 2025-04-30 14:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0002_messagereadstatus_chat_room_m_user_id_85d402_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatroom',
            name='chat_room_c_is_grou_19277e_idx',
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['is_group', 'created_at', 'last_message'], name='chat_room_c_is_grou_323a2e_idx'),
        ),
    ]
