version: "3.9"

services:
  web:
    build: .
    env_file:
      - .env
    command: uvicorn Django_Chat.asgi:application --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=rediss://default:ATeRAAIjcDE4NmQxOGE2YmNiZGI0Y2EyOGQwZjkyZjQ1M2M2ZDVjOXAxMA@welcomed-boa-14225.upstash.io:6379

    depends_on:
      - redis
      - db

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  db:
    image: postgres:14
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
