# Generated by Django 5.2 on 2025-04-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0002_user_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='online_status',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
