# Generated by Django 5.2 on 2025-05-02 10:42

import user_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_user_friends_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pic/default.png', null=True, upload_to=user_api.models.user_profile_pic_path),
        ),
    ]
