# Generated by Django 5.2 on 2025-05-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0006_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_seen',
        ),
        migrations.RemoveField(
            model_name='user',
            name='online_status',
        ),
    ]
