# Generated by Django 5.2 on 2025-05-11 14:16

import cloudinary_storage.storage
import user_api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/profile_pic/default.png', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=user_api.models.user_profile_pic_path),
        ),
    ]
