name: Ping Server

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping the server
        run: |
          echo "Pinging server..."
          curl -s -o /dev/null -w "%{http_code}" https://djangochatapi.onrender.com/ping/

